export const DISPLAY_ITEMS="DISPLAY_ITEMS"
export const CLEAR_DATA="CLEAR_DATA"
export const REMOVE_ITEM="REMOVE_ITEM"
export const LOADING="LOADING"
export const ADD_ONE="ADD_ONE"
export const TAKE_ONE="TAKE_ONE"
